#!/usr/bin/env python3
"""
Odoo development environment CLI.

Manages Odoo processes inside the running `odoo` container (via `docker compose
exec`). One container can host several Odoo instances at once, each named after
its project (-p). Without -p, commands target the 'default' instance.

Every named instance gets its own *instance environment* — a private addons
directory plus an odoo.conf pointing at it — so concurrent instances (e.g. one
per agent) never see each other's modules:

    odoo/auto/instances/<instance>/     (container: /opt/odoo/auto/instances/...)
        addons/     symlinks to the modules in container_configs/<instance>.txt
        odoo.conf   copy of odoo/auto/odoo.conf with addons_path =
                    <this addons dir>,/opt/odoo/custom/src/odoo/addons

Lifecycle: (re)built by `start -p`, `restart -p` and `workon`; built on demand by
`exec -p` / `shell -p`; removed by `stop` and on leaving `workon`. The 'default'
instance has no environment and uses doodba's global /opt/odoo/auto/odoo.conf
(community + src/private addons).

Two ways to work on a project:
  start -p      agents/scripts: Odoo runs in the background; iterate with `restart`.
  workon        developers: opens a shell in the container where you run
                `odoo -d DB -i MODULE` yourself (see _WORKON_RC_TEMPLATE).

Usage:
    python odoo-cli.py <command> [options]

Run `python odoo-cli.py --help` for the full command list.
"""

import argparse
import contextlib
import fcntl
import json
import os
import pathlib
import re
import shutil
import socket
import subprocess
import sys
import time

# ── constants ────────────────────────────────────────────────────────────────

# Ensure docker compose runs from the project root regardless of CWD
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

COMPOSE = ["docker", "compose", "--project-directory", PROJECT_DIR]
SERVICE = "odoo"

# Bind mounts (devel.yaml): odoo/custom → /opt/odoo/custom (ro),
#                           odoo/auto   → /opt/odoo/auto   (rw)
HOST_CUSTOM = pathlib.Path(PROJECT_DIR) / "odoo" / "custom"
CONTAINER_CUSTOM = "/opt/odoo/custom"
HOST_AUTO = pathlib.Path(PROJECT_DIR) / "odoo" / "auto"
CONTAINER_AUTO = "/opt/odoo/auto"

CONFIG_DIR = pathlib.Path(PROJECT_DIR) / "container_configs"

# Global odoo.conf, regenerated by the doodba entrypoint on every container start.
# Instance configs are derived from it, so they are refreshed on every `start`.
BASE_CONF = HOST_AUTO / "odoo.conf"
# Per-instance environments; symlinks inside are relative, so they resolve both on
# the host and in the container (auto/ and custom/ are sibling mounts).
INSTANCES_DIR = HOST_AUTO / "instances"
CORE_ADDONS = f"{CONTAINER_CUSTOM}/src/odoo/addons"

# Per-instance runtime files:
#   /tmp/odoo-{instance}.pid            (container) 3 lines: pid, db, port
#   /opt/odoo/auto/odoo-{instance}.log  (host: odoo/auto/odoo-{instance}.log)
LOG_DIR = CONTAINER_AUTO

DEFAULT_PORT = 8069
PORT_POOL = range(8070, 8100)  # 30 slots for named instances

DEFAULT_FLAGS = [
    "--workers=0",
    "--dev=reload,qweb,werkzeug,xml,access",
    "--limit-memory-soft=0",
    "--limit-time-real=9999999",
    "--limit-time-real-cron=9999999",
]

# Odoo CLI flag used to bind the HTTP port: --xmlrpc-port up to Odoo 18,
# --http-port since Odoo 19.
PORT_FLAG = "--http-port"

# Traefik file provider: one YAML per running instance in TRAEFIK_DYNAMIC_DIR maps
# {instance}.{base} (or the bare base for 'default') to the instance's port.
TRAEFIK_DYNAMIC_DIR = pathlib.Path.home() / ".traefik" / "dynamic"
TRAEFIK_BASE_HOSTNAME = "odoo-20.localhost"

# Host-side flock serializing sequences that must not interleave between
# concurrent odoo-cli.py runs (e.g. several agents): port assignment + PID file +
# route in `start`, and the build/swap of an instance environment.
LOCK_FILE = pathlib.Path.home() / ".cache" / "odoo-cli" / "instances.lock"

# rc file for the interactive `workon` shell; its path doubles as the marker used
# to detect open workon shells (see _workon_instances).
WORKON_RC = "/tmp/.odoo-cli-workon-{instance}.rc"

# ── helpers ───────────────────────────────────────────────────────────────────


def _exec(cmd, *, interactive=False, check=True, capture=False, env=None, **kwargs):
    """Run *cmd* inside the odoo container via docker compose exec.

    *env* is a dict of extra environment variables for the command.
    """
    tty_flags = ["-it"] if interactive else ["-T"]
    env_flags = [f for k, v in (env or {}).items() for f in ("-e", f"{k}={v}")]
    full = COMPOSE + ["exec"] + tty_flags + env_flags + [SERVICE] + cmd
    if capture:
        return subprocess.run(
            full, check=check, text=True, capture_output=True, **kwargs
        )
    return subprocess.run(full, check=check, **kwargs)


def _container_running():
    """Return True if the odoo container itself is up."""
    r = subprocess.run(
        COMPOSE + ["ps", "--status", "running", "--services"],
        check=False,
        text=True,
        capture_output=True,
    )
    return SERVICE in r.stdout.splitlines()


def _ensure_container():
    """Start the containers if needed and wait for the doodba entrypoint to finish.

    The entrypoint (a Python script) links the global addons and writes BASE_CONF
    before exec'ing the container command, so while it runs BASE_CONF may be
    missing or stale. The pattern skips docker-init (`init: true`), whose
    cmdline also names the entrypoint.
    """
    if not _container_running():
        print("Starting containers...")
        subprocess.run(COMPOSE + ["up", "-d"], check=True)
    for _ in range(120):
        r = _exec(
            [
                "bash",
                "-c",
                "pgrep -f '^[^ ]*python[^ ]* /opt/odoo/common/entrypoint'"
                " >/dev/null || echo ready",
            ],
            capture=True,
            check=False,
        )
        if r.stdout.strip() == "ready":
            return
        time.sleep(1)
    print("ERROR: container entrypoint did not finish within 120s.", file=sys.stderr)
    sys.exit(1)


def _require_container():
    if not _container_running():
        print(
            "ERROR: The odoo container is not running. Run: docker compose up -d",
            file=sys.stderr,
        )
        sys.exit(1)


def _rel(path):
    """Return *path* relative to PROJECT_DIR for display."""
    return pathlib.Path(path).relative_to(PROJECT_DIR)


# ── instance helpers ──────────────────────────────────────────────────────────


def _instance(args):
    """Return the instance name from args, defaulting to 'default'."""
    return getattr(args, "project", None) or "default"


@contextlib.contextmanager
def _instances_lock():
    """Hold the host-side LOCK_FILE flock for the duration of the block."""
    LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(LOCK_FILE, "w") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(f, fcntl.LOCK_UN)


def _pid_file(instance):
    return f"/tmp/odoo-{instance}.pid"


def _log_file(instance):
    return f"{LOG_DIR}/odoo-{instance}.log"


def _host_port(container_port):
    """Convert a container port to its host-mapped port using PORT_PREFIX from .env."""
    prefix = "20"
    env_file = pathlib.Path(PROJECT_DIR) / ".env"
    try:
        for line in env_file.read_text().splitlines():
            if line.strip().startswith("PORT_PREFIX="):
                prefix = line.split("=", 1)[1].strip()
                break
    except FileNotFoundError:
        pass
    # 8069 → 20069, 8070 → 20070, etc.
    return f"{prefix}{str(container_port)[1:]}"


def _is_running(instance):
    """Return True if a live Odoo process exists for *instance* inside the container.

    Besides `kill -0`, the PID's /proc cmdline must contain the recorded port:
    containers (and their /tmp) survive `docker compose down`/`up`, so a stale
    PID file could otherwise match an unrelated process that reused the PID.
    """
    pid_file = _pid_file(instance)
    script = (
        f"[ -f {pid_file} ] || exit 1\n"
        f"pid=$(sed -n '1p' {pid_file})\n"
        f"port=$(sed -n '3p' {pid_file})\n"
        f'kill -0 "$pid" 2>/dev/null || exit 1\n'
        f'[ -z "$port" ] && exit 0\n'
        f'grep -q -- "{PORT_FLAG}=$port" "/proc/$pid/cmdline" 2>/dev/null\n'
    )
    return _exec(["bash", "-c", script], check=False).returncode == 0


def _read_pid_meta(instance):
    """Return (pid, db, port) from *instance*'s PID file, or (None, None, None)."""
    r = _exec(
        ["bash", "-c", f"cat {_pid_file(instance)} 2>/dev/null"],
        capture=True,
        check=False,
    )
    lines = r.stdout.strip().splitlines()
    try:
        pid = int(lines[0])
    except (ValueError, IndexError):
        return None, None, None
    db = lines[1].strip() if len(lines) > 1 and lines[1].strip() else None
    port_str = lines[2].strip() if len(lines) > 2 else ""
    port = int(port_str) if port_str.isdigit() else None
    return pid, db, port


def _list_instances():
    """Return all live Odoo instances as [{instance, pid, db, port}].

    Same liveness test as _is_running (PID alive and cmdline has the port).
    """
    script = (
        "for f in /tmp/odoo-*.pid; do\n"
        '    [ -f "$f" ] || continue\n'
        "    pid=$(sed -n '1p' \"$f\")\n"
        '    kill -0 "$pid" 2>/dev/null || continue\n'
        "    port=$(sed -n '3p' \"$f\")\n"
        '    if [ -n "$port" ]; then\n'
        f'        grep -q -- "{PORT_FLAG}=$port" "/proc/$pid/cmdline" \\\n'
        "            2>/dev/null || continue\n"
        "    fi\n"
        '    name=$(basename "$f" .pid); name=${name#odoo-}\n'
        "    db=$(sed -n '2p' \"$f\")\n"
        '    echo "$name|$pid|$db|$port"\n'
        "done\n"
    )
    r = _exec(["bash", "-c", script], capture=True, check=False)
    instances = []
    for line in r.stdout.strip().splitlines():
        parts = line.split("|")
        if len(parts) < 2:
            continue
        try:
            pid = int(parts[1])
        except ValueError:
            continue
        db = parts[2] if len(parts) > 2 and parts[2] else None
        port_str = parts[3] if len(parts) > 3 else ""
        port = int(port_str) if port_str.isdigit() else None
        instances.append({"instance": parts[0], "pid": pid, "db": db, "port": port})
    return instances


def _workon_instances():
    """Return the set of instances that currently have an open `workon` shell,
    found by the `bash --rcfile <WORKON_RC>` command line of the shell."""
    prefix = WORKON_RC.split("{")[0]
    r = _exec(["pgrep", "-af", "--", f"--rcfile {prefix}"], capture=True, check=False)
    return set(re.findall(rf"--rcfile {re.escape(prefix)}(\S+)\.rc", r.stdout))


def _print_instances_error(instances):
    print("ERROR: Multiple instances running — specify -p PROJECT:", file=sys.stderr)
    for i in instances:
        detail = f"  {i['instance']:<16} PID {i['pid']}"
        if i["db"]:
            detail += f", DB {i['db']}"
        if i["port"]:
            detail += f", port {i['port']}"
        print(detail, file=sys.stderr)


def _auto_detect_instance():
    """Return the instance name when exactly one is running, else print an error
    and return None."""
    instances = _list_instances()
    if len(instances) == 1:
        return instances[0]["instance"]
    if not instances:
        print("ERROR: No Odoo instance is running. Use 'start' first.", file=sys.stderr)
    else:
        _print_instances_error(instances)
    return None


def _assign_port(instance):
    """Return DEFAULT_PORT for 'default', else the lowest free port in PORT_POOL."""
    if instance == "default":
        return DEFAULT_PORT
    used = {i["port"] for i in _list_instances() if i["port"]}
    for port in PORT_POOL:
        if port not in used:
            return port
    print(
        f"WARNING: port pool {PORT_POOL.start}–{PORT_POOL.stop - 1} exhausted,"
        f" reusing {PORT_POOL.start}.",
        file=sys.stderr,
    )
    return PORT_POOL.start


def _kill_instance(instance):
    """Kill the Odoo process for *instance* and remove its PID file."""
    pid_file = _pid_file(instance)
    _exec(["bash", "-c", f"kill \"$(sed -n '1p' {pid_file})\"; rm -f {pid_file}"])


# ── instance environments ─────────────────────────────────────────────────────


def _instance_dir(instance):
    return INSTANCES_DIR / instance


def _instance_conf(instance):
    """Container path of the instance's odoo.conf."""
    return f"{CONTAINER_AUTO}/instances/{instance}/odoo.conf"


def _has_instance_env(instance):
    return (_instance_dir(instance) / "addons").is_dir()


def _build_instance_env(instance, desired):
    """(Re)build the instance environment: addons/ symlink dir + odoo.conf.

    The new addons dir is built beside the old one and swapped in, so an instance
    already running on it never sees a half-populated directory.
    """
    inst = _instance_dir(instance)
    addons = inst / "addons"
    new = inst / f"addons.new-{os.getpid()}"
    old = inst / f"addons.old-{os.getpid()}"
    with _instances_lock():
        inst.mkdir(parents=True, exist_ok=True)
        shutil.rmtree(new, ignore_errors=True)
        new.mkdir()
        for name, module_path in desired.items():
            (new / name).symlink_to(os.path.relpath(module_path, addons))
        if addons.exists():
            addons.rename(old)
        new.rename(addons)
        shutil.rmtree(old, ignore_errors=True)
        _write_instance_conf(instance)


def _write_instance_conf(instance):
    """Write the instance odoo.conf: BASE_CONF with addons_path pointing at the
    instance addons dir (omitted when empty — Odoo rejects module-less paths)
    followed by the community addons."""
    if not BASE_CONF.is_file():
        print(
            f"ERROR: {_rel(BASE_CONF)} not found — the doodba entrypoint writes it"
            " on container start. Run: docker compose up -d",
            file=sys.stderr,
        )
        sys.exit(1)
    inst = _instance_dir(instance)
    paths = [CORE_ADDONS]
    if any((inst / "addons").iterdir()):
        paths.insert(0, f"{CONTAINER_AUTO}/instances/{instance}/addons")
    line = f"addons_path = {','.join(paths)}"
    base = BASE_CONF.read_text()
    conf, n = re.subn(r"(?m)^addons_path\s*=.*$", line, base)
    if not n:
        conf = base.replace("[options]", f"[options]\n{line}", 1)
    tmp = inst / f"odoo.conf.{os.getpid()}"
    tmp.write_text(conf)
    tmp.replace(inst / "odoo.conf")


def _remove_instance_env(instance):
    shutil.rmtree(_instance_dir(instance), ignore_errors=True)


def _odoo_env(instance):
    """Environment that makes any `odoo`/`click-odoo` invocation in the container
    use *instance*'s config. ODOO_RC takes precedence over the image's
    OPENERP_SERVER (Odoo 18); also setting OPENERP_SERVER makes Odoo 20+ log a
    deprecation warning."""
    return {"ODOO_RC": _instance_conf(instance)}


def _ensure_instance_env(instance):
    """Return the ODOO_RC env for *instance*, building its environment first if
    it doesn't exist yet (it then persists until `stop -p`)."""
    if not _has_instance_env(instance):
        _setup_project(instance)
    return _odoo_env(instance)


# ── project setup ─────────────────────────────────────────────────────────────
#
# _setup_project(project) is run by `start -p`, `restart -p` and `workon`:
#   1. Parse container_configs/<project>.txt (host-side, no side effects;
#      exits listing available projects if missing).
#   2. Start the containers if needed (BASE_CONF, [setup] and pip need them).
#   3. Build the instance environment (addons symlinks + odoo.conf).
#   4. Run [setup] scripts as root, then `pip install -r` each [requirements].
#      pip installs into the shared container site-packages.


def _config_file(project):
    config_file = CONFIG_DIR / f"{project}.txt"
    if not config_file.exists():
        print(f"ERROR: container_configs/{project}.txt not found.", file=sys.stderr)
        available = sorted(
            f.stem
            for f in CONFIG_DIR.iterdir()
            if f.suffix == ".txt" and not f.name.startswith(".")
        )
        if available:
            print(f"Available projects: {', '.join(available)}", file=sys.stderr)
        sys.exit(1)
    return config_file


def _setup_project(project):
    """Build *project*'s instance environment and install its dependencies."""
    config_file = _config_file(project)
    desired, err_collect = _collect_desired(config_file)
    req_paths, err_req = _collect_requirements(config_file)
    setup_paths, err_setup = _collect_setup(config_file)
    if err_collect or err_req or err_setup:
        sys.exit(1)

    _ensure_container()

    print(f"Building instance environment for '{project}'...")
    _build_instance_env(project, desired)
    print(f"  {len(desired)} module(s) linked in {_rel(_instance_dir(project))}/addons")

    for script in setup_paths:
        print(f"Running setup script: bash {_rel(script)}")
        subprocess.run(
            COMPOSE + ["exec", "-T", "--user", "root", SERVICE, "bash"],
            input=script.read_text(),
            text=True,
            check=True,
        )

    for req in req_paths:
        print(f"Installing requirements: pip install -r {req}")
        _exec(["pip", "install", "--no-cache-dir", "-r", req])


def _parse_config(config_file):
    """Parse a container config .txt file into {section: [lines]}.

    Sections: [addons], [requirements], [setup]. Lines before the first header
    belong to [addons]. Comments (#) and blank lines are ignored.
    """
    sections: dict[str, list[str]] = {"addons": [], "requirements": [], "setup": []}
    current = "addons"
    for raw in config_file.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].lower()
            sections.setdefault(current, [])
        else:
            sections[current].append(line)
    return sections


def _collect_desired(config_file):
    """Return ({module_name: host_path}, error_count) for the [addons] entries.

    Every immediate, non-dot subdirectory of each listed directory is a module.
    Later entries win on name clashes. Paths must resolve under odoo/custom/,
    or the symlinks would dangle inside the container.
    """
    desired: dict[str, pathlib.Path] = {}
    errors = 0
    src = _rel(config_file)
    for line in _parse_config(config_file)["addons"]:
        path = (pathlib.Path(PROJECT_DIR) / line).resolve()
        if not path.is_dir():
            kind = "NOT_DIR" if path.exists() else "MISSING"
            print(f"  {kind}  {path}  (from {src})")
            errors += 1
            continue
        if not path.is_relative_to(HOST_CUSTOM):
            print(f"  OUT_OF_MOUNT  {path} is not under odoo/custom/  (from {src})")
            errors += 1
            continue
        for module_path in sorted(path.iterdir()):
            if module_path.is_dir() and not module_path.name.startswith("."):
                desired[module_path.name] = module_path
    return desired, errors


def _collect_requirements(config_file):
    """Return ([container_paths], error_count) for the [requirements] entries."""
    req_paths: list[str] = []
    errors = 0
    src = _rel(config_file)
    for line in _parse_config(config_file)["requirements"]:
        host_path = (pathlib.Path(PROJECT_DIR) / line).resolve()
        if not host_path.exists():
            print(f"  MISSING  {host_path}  (from {src})")
            errors += 1
            continue
        if not host_path.is_relative_to(HOST_CUSTOM):
            print(
                f"  OUT_OF_MOUNT  {host_path} is not under odoo/custom/  (from {src})"
            )
            errors += 1
            continue
        req_paths.append(f"{CONTAINER_CUSTOM}/{host_path.relative_to(HOST_CUSTOM)}")
    return req_paths, errors


def _collect_setup(config_file):
    """Return ([host_path], error_count) for the [setup] script entries.

    Scripts are piped to bash via stdin, so they may live anywhere on the host.
    """
    script_paths: list[pathlib.Path] = []
    errors = 0
    src = _rel(config_file)
    for line in _parse_config(config_file)["setup"]:
        host_path = (pathlib.Path(PROJECT_DIR) / line).resolve()
        if not host_path.exists():
            print(f"  MISSING  {host_path}  (from {src})")
            errors += 1
            continue
        script_paths.append(host_path)
    return script_paths, errors


# ── static manifest check ─────────────────────────────────────────────────────
#
# `check` catches, in seconds and without a database, three failures that
# otherwise only surface after a multi-minute registry boot:
#   - a module name that doesn't exist on the addons path
#   - a missing/unimportable external_dependencies.python package
#   - a manifest `excludes` conflict inside the dependency closure
# It runs in the container (the only place that sees the real addons path and
# pip packages) using Odoo's own odoo.modules.module helpers.

_MANIFEST_CHECK_SCRIPT = r"""
import json
import sys

import odoo
from odoo.tools import config as _config

_config.parse_config(["-c", sys.argv[2]])

from odoo.modules.module import (
    check_python_external_dependency,
    get_manifest,
    initialize_sys_path,
)

initialize_sys_path()

roots = json.loads(sys.argv[1])

manifests = {}
missing_modules = []
queue = list(roots)
while queue:
    name = queue.pop()
    if name in manifests or name in missing_modules:
        continue
    manifest = get_manifest(name)
    if not manifest:
        missing_modules.append(name)
        continue
    manifests[name] = dict(manifest)
    for dep in manifest.get("depends", []):
        if dep not in manifests and dep not in missing_modules:
            queue.append(dep)

missing_pydeps = {}
for name, manifest in manifests.items():
    for pydep in (manifest.get("external_dependencies") or {}).get("python", []):
        try:
            check_python_external_dependency(pydep)
        except Exception as e:  # Odoo 20 raises bare Exception here
            missing_pydeps.setdefault(name, []).append(str(e))

closure = set(manifests)
conflicts = set()
for name, manifest in manifests.items():
    for excluded in manifest.get("excludes", []):
        if excluded in closure:
            conflicts.add(tuple(sorted((name, excluded))))

print(json.dumps({
    "roots": sorted(roots),
    "closure_size": len(manifests),
    "missing_modules": sorted(set(missing_modules)),
    "missing_python_deps": missing_pydeps,
    "conflicts": sorted(conflicts),
}))
"""


def _run_manifest_check(roots, conf):
    """Run _MANIFEST_CHECK_SCRIPT in the container for *roots* against the
    odoo.conf at container path *conf*. Returns the parsed result dict."""
    r = _exec(
        ["python3", "-c", _MANIFEST_CHECK_SCRIPT, json.dumps(roots), conf],
        capture=True,
        check=False,
    )
    if r.returncode != 0:
        print(r.stderr or r.stdout, file=sys.stderr)
        print(
            "ERROR: manifest check failed to run inside the container.", file=sys.stderr
        )
        sys.exit(1)
    try:
        return json.loads(r.stdout.strip().splitlines()[-1])
    except (ValueError, IndexError):
        print(r.stdout, file=sys.stderr)
        print("ERROR: could not parse manifest check output.", file=sys.stderr)
        sys.exit(1)


# ── traefik routing ───────────────────────────────────────────────────────────


def _compose_project():
    """Return COMPOSE_PROJECT_NAME from .env (fallback: directory name)."""
    env_file = pathlib.Path(PROJECT_DIR) / ".env"
    try:
        for line in env_file.read_text().splitlines():
            if line.strip().startswith("COMPOSE_PROJECT_NAME="):
                return line.split("=", 1)[1].strip()
    except FileNotFoundError:
        pass
    return pathlib.Path(PROJECT_DIR).name.lower()


def _traefik_hostname(instance):
    """'default' → odoo-20.localhost; 'samotics' → samotics.odoo-20.localhost."""
    if instance == "default":
        return TRAEFIK_BASE_HOSTNAME
    return f"{instance}.{TRAEFIK_BASE_HOSTNAME}"


def _write_traefik_route(instance, port):
    """Write (or overwrite) the Traefik route for this instance; return its hostname.

    Traefik watches TRAEFIK_DYNAMIC_DIR and hot-reloads within ~100ms.
    """
    TRAEFIK_DYNAMIC_DIR.mkdir(parents=True, exist_ok=True)
    hostname = _traefik_hostname(instance)
    project = _compose_project()
    container = f"{project}-odoo-1"
    router = f"{project}-{instance}"
    route_file = TRAEFIK_DYNAMIC_DIR / f"{router}.yml"
    route_file.write_text(
        f"# Auto-generated by odoo-cli.py — instance: {instance}  port: {port}\n"
        f"http:\n"
        f"  routers:\n"
        f"    {router}:\n"
        f"      rule: 'Host(`{hostname}`)'\n"
        f"      service: {router}\n"
        f"      entryPoints:\n"
        f"        - http\n"
        f"  services:\n"
        f"    {router}:\n"
        f"      loadBalancer:\n"
        f"        servers:\n"
        f'          - url: "http://{container}:{port}"\n'
    )
    return hostname


def _remove_traefik_route(instance):
    """Delete the Traefik route for this instance if it exists."""
    route_file = TRAEFIK_DYNAMIC_DIR / f"{_compose_project()}-{instance}.yml"
    route_file.unlink(missing_ok=True)


def _prune_stale_traefik_routes(keep=None):
    """Remove this project's routes whose instance is neither running, held by an
    open `workon` shell, nor *keep* (the instance about to be (re)started).

    Routes are otherwise only removed by `stop`; a container recreation or a
    process killed outside odoo-cli.py would leave Traefik pointing at a dead
    (or since-reused) port.
    """
    if not TRAEFIK_DYNAMIC_DIR.is_dir():
        return
    prefix = f"{_compose_project()}-"
    live = {i["instance"] for i in _list_instances()} | _workon_instances() | {keep}
    for route_file in TRAEFIK_DYNAMIC_DIR.glob(f"{prefix}*.yml"):
        if route_file.stem[len(prefix) :] not in live:
            route_file.unlink()
            print(f"Pruned stale Traefik route: {route_file.name}", file=sys.stderr)


def _check_hosts_entry(hostname):
    """Print /etc/hosts instructions only if *hostname* doesn't resolve.

    systemd-resolved and mDNSResponder resolve any *.localhost name to loopback
    (RFC 6761), so this normally prints nothing.
    """
    try:
        socket.getaddrinfo(hostname, None)
        return
    except socket.gaierror:
        pass
    print(
        f"\n  '{hostname}' does not resolve on this system. Add it to /etc/hosts:\n"
        f"    echo '127.0.0.1 {hostname}' | sudo tee -a /etc/hosts"
    )


# ── commands ──────────────────────────────────────────────────────────────────


def cmd_start(args):
    if getattr(args, "project", None) and not getattr(args, "_no_setup", False):
        _setup_project(args.project)
    _require_container()

    instance = _instance(args)

    with _instances_lock():
        _prune_stale_traefik_routes(keep=instance)
        if _is_running(instance):
            print(
                f"Odoo instance '{instance}' is already running."
                " Use 'restart' to restart it."
            )
            sys.exit(0)

        db = args.database
        port = getattr(args, "port", None) or _assign_port(instance)
        log_file = _log_file(instance)
        pid_file = _pid_file(instance)

        flags = list(DEFAULT_FLAGS) + [f"{PORT_FLAG}={port}"]
        if _has_instance_env(instance):
            # Refresh against BASE_CONF, which a container restart may have changed.
            _write_instance_conf(instance)
            flags = ["-c", _instance_conf(instance)] + flags
        if db:
            # Serve only this DB, so the instance URL opens it directly instead
            # of the database selector (the db container also creates `devel`).
            flags += ["-d", db, f"--db-filter=^{db}$"]
        if getattr(args, "install", None):
            flags += ["-i", ",".join(args.install)]
        if getattr(args, "update", None):
            flags += ["-u", ",".join(args.update)]

        odoo_cmd = "odoo " + " ".join(flags)
        launch = (
            f"nohup {odoo_cmd} > {log_file} 2>&1 & "
            f"_PID=$! && "
            f'printf "%s\\n%s\\n%s\\n" "$_PID" "{db or ""}" "{port}" > {pid_file} && '
            f"echo \"Odoo instance '{instance}' started (PID $_PID, port {port}). "
            f'Logs: {log_file}"'
        )
        _exec(["bash", "-c", launch])
        hostname = _write_traefik_route(instance, port)
    _check_hosts_entry(hostname)


def cmd_stop(args):
    """Stop the instance and remove its route and environment — unless a
    `workon` shell for it is still open, which keeps both."""
    instance = getattr(args, "project", None) or _auto_detect_instance()
    if not instance:
        sys.exit(1)

    if _is_running(instance):
        _kill_instance(instance)
        print(f"Odoo instance '{instance}' stopped.")
    else:
        print(f"Odoo instance '{instance}' is not running.")

    if instance in _workon_instances():
        print(f"Kept route and environment: a `workon {instance}` shell is open.")
        return
    _remove_traefik_route(instance)
    _remove_instance_env(instance)


def cmd_restart(args):
    """Stop and start an instance. With -p the instance environment is rebuilt
    (like `start -p`); without -p the instance is auto-detected and relaunched
    on its existing environment."""
    explicit_project = getattr(args, "project", None)
    if explicit_project:
        instance = explicit_project
    else:
        instances = _list_instances()
        if len(instances) > 1:
            _print_instances_error(instances)
            sys.exit(1)
        instance = instances[0]["instance"] if instances else "default"
        args.project = instance if instance != "default" else None
        args._no_setup = True

    # Infer -d and --port from the PID file when not given
    _, stored_db, stored_port = _read_pid_meta(instance)
    if not args.database and stored_db:
        args.database = stored_db
        print(f"Using database '{stored_db}' from instance metadata.")
    if not getattr(args, "port", None) and stored_port:
        args.port = stored_port

    if _is_running(instance):
        _kill_instance(instance)
        print("Stopped. Waiting for process to exit...")
        time.sleep(2)

    cmd_start(args)


def cmd_status(args):
    if not _container_running():
        print("Container: not running")
        return
    print("Container: running")

    instance = getattr(args, "project", None)
    use_json = getattr(args, "json", False)

    if instance:
        pid, db, port = _read_pid_meta(instance)
        running = _is_running(instance)
        env = (
            str(_rel(_instance_dir(instance))) if _has_instance_env(instance) else None
        )
        if use_json:
            print(
                json.dumps(
                    {
                        "instance": instance,
                        "pid": pid,
                        "db": db,
                        "port": port,
                        "running": running,
                        "env": env,
                    }
                )
            )
            return
        print(f"Instance:  {instance}")
        print(f"Env:       {env or '— (global odoo.conf)'}")
        if running:
            print(f"Odoo:      running (PID {pid})")
            if db:
                print(f"Database:  {db}")
            if port:
                print(f"Port:      {port}")
                print(f"URL:       http://{_traefik_hostname(instance)}")
                print(f"Direct:    http://127.0.0.1:{_host_port(port)}")
            print(f"Logs:      ./odoo/auto/odoo-{instance}.log")
        else:
            print("Odoo:      not running")
        return

    _prune_stale_traefik_routes()
    instances = _list_instances()
    if use_json:
        print(json.dumps(instances))
        return
    if not instances:
        print("Odoo:      not running")
        return

    col_i = max(len("INSTANCE"), max(len(i["instance"]) for i in instances))
    col_p = max(len("PID"), max(len(str(i["pid"])) for i in instances))
    col_d = max(len("DATABASE"), max(len(i["db"] or "—") for i in instances))
    col_o = len("PORT")
    fmt = f"{{:<{col_i}}}  {{:<{col_p}}}  {{:<{col_d}}}  {{:<{col_o}}}"
    print(fmt.format("INSTANCE", "PID", "DATABASE", "PORT"))
    print(fmt.format("─" * col_i, "─" * col_p, "─" * col_d, "─" * col_o))
    for i in instances:
        print(
            fmt.format(
                i["instance"],
                str(i["pid"]),
                i["db"] or "—",
                str(i["port"]) if i["port"] else "—",
            )
        )


def cmd_logs(args):
    _require_container()
    instance = getattr(args, "project", None) or _auto_detect_instance()
    if not instance:
        sys.exit(1)

    log_file = _log_file(instance)
    flags = f"-n {args.lines}" + (" -f" if args.follow else "")
    no_log_msg = f"No log file yet — start instance '{instance}' first."
    bash = f"tail {flags} {log_file} 2>/dev/null || echo '{no_log_msg}'"
    _exec(["bash", "-c", bash], interactive=args.follow)


def cmd_pip(args):
    _require_container()
    running = [i["instance"] for i in _list_instances()]
    if len(running) > 1:
        print(
            "WARNING: site-packages are shared by the whole container — this "
            f"install affects every running instance: {', '.join(running)}",
            file=sys.stderr,
        )
    _exec(["pip", "install", "--no-cache-dir"] + args.packages)
    print(
        "\nNote: this install is ephemeral (lost on container recreate).\n"
        "For persistence, add it to odoo/custom/dependencies/pip.txt\n"
        "and run: docker compose build"
    )


def cmd_shell(args):
    """Odoo shell; with -p it uses the instance's addons and (by default) its DB."""
    env = None
    db = args.database
    if args.project:
        env = _ensure_instance_env(args.project)
        db = db or _read_pid_meta(args.project)[1]
    _require_container()
    db_flag = ["-d", db] if db else []
    _exec(["odoo", "shell"] + db_flag, interactive=True, env=env)


def cmd_exec(args):
    """Run an arbitrary command inside the container; with -p, `odoo` in that
    command uses the instance's addons (ODOO_RC is set; the environment is built
    if missing)."""
    cmd = args.cmd[1:] if args.cmd and args.cmd[0] == "--" else args.cmd
    if not cmd:
        print("ERROR: Provide a command to run.", file=sys.stderr)
        sys.exit(1)
    env = _ensure_instance_env(args.project) if args.project else None
    _exec(cmd, interactive=sys.stdin.isatty(), env=env)


# Bash rc for the `workon` shell. ODOO_RC makes every `odoo`/`click-odoo` use the
# instance's addons. The `odoo()` wrapper gives server runs DEFAULT_FLAGS (before
# the user's, so theirs win), the instance port, a PID file and the instance log,
# so status/logs/stop/restart and Traefik see them. Subcommands (`odoo shell`, ...)
# pass straight through.
_WORKON_RC_TEMPLATE = """[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"
export ODOO_RC="__CONF__"
PS1="(__INSTANCE__) $PS1"
odoo() {
    case "${1:-}" in
        server) shift ;;
        "" | -*) ;;
        *) command odoo "$@"; return ;;
    esac
    if [ ! -f "$ODOO_RC" ]; then
        echo "workon: instance environment removed (stop?); exit and rerun workon" >&2
        return 1
    fi
    local _db="" _args=("$@") _i
    for ((_i = 0; _i < ${#_args[@]}; _i++)); do
        case "${_args[$_i]}" in
            -d | --database) _db="${_args[$((_i + 1))]}" ;;
            -d* ) _db="${_args[$_i]#-d}" ;;
            --database=*) _db="${_args[$_i]#--database=}" ;;
        esac
    done
    local _filter=()
    [ -n "$_db" ] && _filter=("--db-filter=^${_db}$")
    # Odoo writes to the instance log; `tail` shows it here without becoming a
    # child of Odoo (which would make Odoo warn about it on shutdown).
    command odoo __DEFAULT_FLAGS__ "${_filter[@]}" "$@" __PORT_FLAG__=__PORT__ \
        > "__LOGFILE__" 2>&1 &
    local _pid=$!
    printf '%s\\n%s\\n%s\\n' "$_pid" "$_db" "__PORT__" > "__PIDFILE__"
    trap 'kill "$_pid" 2>/dev/null' INT
    # Ctrl+C only reaches the foreground `tail`; once it ends, stop Odoo too
    # (no-op if Odoo already exited, e.g. with --stop-after-init).
    tail -n +1 -f --pid="$_pid" "__LOGFILE__"
    kill "$_pid" 2>/dev/null
    wait "$_pid"; local _rc=$?
    trap - INT
    # Only remove the PID file if it is still ours (restart may have replaced it)
    [ "$(sed -n 1p "__PIDFILE__" 2>/dev/null)" = "$_pid" ] && rm -f "__PIDFILE__"
    return $_rc
}
cat << 'EOF'
────────────────────────────────────────────────────────────────────────────
workon __INSTANCE__ → http://__HOSTNAME__   (Odoo is not running yet)

  odoo -d DB -i MODULE    install and serve     Ctrl+C   stop Odoo
  odoo -d DB -u MODULE    update and serve      exit     leave (cleans up)
  odoo shell -d DB        REPL on the same addons

  Details: python3 odoo-cli.py workon --help
────────────────────────────────────────────────────────────────────────────
EOF
"""


def _workon_help():
    """Description for `workon --help` (built from this environment's constants)."""
    dyn = str(TRAEFIK_DYNAMIC_DIR).replace(str(pathlib.Path.home()), "~")
    host = f"PROJECT.{TRAEFIK_BASE_HOSTNAME}"
    return f"""\
Run a project's Odoo by hand and test it in a browser, served by Traefik at
  http://{host}

workon PROJECT:
  1. builds the instance environment from container_configs/PROJECT.txt
     (addons symlinks + odoo.conf), runs [setup] and pip [requirements]
  2. picks a port ({PORT_POOL.start}-{PORT_POOL.stop - 1}) and writes the Traefik route
     {dyn}/{_compose_project()}-PROJECT.yml
  3. opens a bash shell in the odoo container; Odoo is NOT started

In that shell:
  odoo -d DB -i MODULE   install MODULE (DB is created if missing) and serve
  odoo -d DB -u MODULE   update MODULE after code changes and serve
  Ctrl+C                 stop Odoo, keep the shell
  odoo shell -d DB       Python REPL on the same addons
  exit                   leave; removes route + environment unless Odoo runs

While Odoo runs, open http://{host}
(a new DB logs in as admin/admin).
`odoo` there gets the project's addons, the instance port, the dev flags of
`start` (auto-reload, one worker; your own flags win), a PID file and the log
odoo/auto/odoo-PROJECT.log, so from another terminal these work:
  odoo-cli.py status | logs -p PROJECT -f | restart -p PROJECT | stop -p PROJECT

Changed container_configs/PROJECT.txt? `exit` and run workon again.

Traefik prerequisites (once per machine):
  - Traefik v3 on the external Docker network "traefik", HTTP on port 80,
    file provider watching {dyn} (--providers.file.watch=true)
  - this stack's odoo container on that network (devel.yaml does this)
  - {host} resolving to 127.0.0.1 (automatic with
    systemd-resolved or macOS; otherwise workon prints the /etc/hosts line)
  Inspect routes in the Traefik dashboard (http://127.0.0.1:8080 with
  --api.insecure).
"""


def cmd_workon(args):
    """Build a project's instance environment and open an interactive shell in it.

    Nothing is started: the developer runs `odoo ...` by hand in the shell (see
    _WORKON_RC_TEMPLATE for what that shell provides). On exit, the environment
    and route are removed unless Odoo is still running for the instance or
    another workon shell for it is open.
    """
    _setup_project(args.project)
    instance = args.project

    _, _, stored_port = _read_pid_meta(instance)
    if _is_running(instance):
        print(
            f"Note: instance '{instance}' is already running (port {stored_port});"
            " `odoo` here would fail to bind it. `stop` or `restart` it instead."
        )
    port = stored_port or _assign_port(instance)
    hostname = _write_traefik_route(instance, port)
    _check_hosts_entry(hostname)

    rc_file = WORKON_RC.format(instance=instance)
    rc_contents = (
        _WORKON_RC_TEMPLATE.replace("__CONF__", _instance_conf(instance))
        .replace("__DEFAULT_FLAGS__", " ".join(DEFAULT_FLAGS))
        .replace("__PORT_FLAG__", PORT_FLAG)
        .replace("__PORT__", str(port))
        .replace("__PIDFILE__", _pid_file(instance))
        .replace("__LOGFILE__", _log_file(instance))
        .replace("__INSTANCE__", instance)
        .replace("__HOSTNAME__", hostname)
    )
    _exec(["bash", "-c", f"cat > {rc_file}"], input=rc_contents.encode())
    _exec(["bash", "--rcfile", rc_file, "-i"], interactive=True, check=False)

    if _is_running(instance) or instance in _workon_instances():
        return
    _remove_traefik_route(instance)
    _remove_instance_env(instance)
    print(f"workon: cleaned up environment and route for '{instance}'.")


def cmd_check(args):
    """Statically validate modules before booting a database (see the comment
    above _MANIFEST_CHECK_SCRIPT).

    -p selects the addons path (the project's, via a throwaway environment;
    default: the global one). -i selects the modules to check; without it, -p
    checks every module the project provides.
    """
    _require_container()

    roots = list(args.install or [])
    tmp_instance = None
    conf = f"{CONTAINER_AUTO}/odoo.conf"
    if args.project:
        desired, err_collect = _collect_desired(_config_file(args.project))
        if err_collect:
            sys.exit(1)
        roots = roots or sorted(desired)
        tmp_instance = f".check-{os.getpid()}"
        _build_instance_env(tmp_instance, desired)
        conf = _instance_conf(tmp_instance)

    roots = sorted(set(roots))
    if not roots:
        print(
            "ERROR: Provide -i MODULE [MODULE ...] and/or -p PROJECT"
            " (checks every module the project provides)",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        result = _run_manifest_check(roots, conf)
    finally:
        if tmp_instance:
            _remove_instance_env(tmp_instance)

    if args.json:
        print(json.dumps(result))
    else:
        print(f"Checked {result['closure_size']} module(s) ({len(roots)} requested)\n")

        if result["missing_modules"]:
            print(f"MISSING MODULES ({len(result['missing_modules'])}):")
            for name in result["missing_modules"]:
                print(f"  {name}  — not found on any addons path")
            print()

        if result["missing_python_deps"]:
            total = sum(len(v) for v in result["missing_python_deps"].values())
            print(f"MISSING PYTHON DEPENDENCIES ({total}):")
            for name, errs in sorted(result["missing_python_deps"].items()):
                for err in errs:
                    print(f"  {name}: {err}")
            print()

        if result["conflicts"]:
            print(f"EXCLUDES CONFLICTS ({len(result['conflicts'])}):")
            for a, b in result["conflicts"]:
                print(f"  {a}  ×  {b}")
            print()

        if not (
            result["missing_modules"]
            or result["missing_python_deps"]
            or result["conflicts"]
        ):
            print(
                "OK — no missing modules, missing Python deps, or excludes conflicts."
            )

    if (
        result["missing_modules"]
        or result["missing_python_deps"]
        or result["conflicts"]
    ):
        sys.exit(1)


# ── argument parser ───────────────────────────────────────────────────────────


def build_parser():
    parser = argparse.ArgumentParser(
        prog="odoo-cli.py",
        description="Manage Odoo instances inside the dev Docker container.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=f"""
examples (python3 odoo-cli.py ...):
  start -p myproject -d mydb -i my_module   background instance (agents, scripts)
  restart -u my_module                      after a code change
  stop -p myproject                         end; removes its environment
  workon myproject                          interactive shell; see workon --help
  exec -p myproject -- odoo -d test_db -u my_module --test-enable \\
      --test-tags :MyTest --stop-after-init --no-http    tests
  check -p myproject -i my_module           static check, no DB
  status [--json]                           running instances
  start -d mydb                             'default' instance, port {DEFAULT_PORT}

Run COMMAND --help for details.
""",
    )

    sub = parser.add_subparsers(dest="subcommand", required=True)

    def add_project(p, help_):
        p.add_argument("-p", "--project", metavar="PROJECT", help=help_)

    def add_modules(p):
        p.add_argument(
            "-i", "--install", nargs="+", metavar="MODULE", help="Modules to install"
        )
        p.add_argument(
            "-u", "--update", nargs="+", metavar="MODULE", help="Modules to update"
        )

    # start
    p = sub.add_parser("start", help="Start an Odoo instance in the background")
    add_project(
        p,
        "Instance name; builds its environment from container_configs/PROJECT.txt,"
        " runs [setup] and [requirements] (starts containers if needed)."
        " Omit for the 'default' instance.",
    )
    p.add_argument("-d", "--database", metavar="DB", help="Database to use")
    p.add_argument(
        "-P",
        "--port",
        metavar="PORT",
        type=int,
        help=(
            f"HTTP port inside the container (default: {DEFAULT_PORT} for 'default',"
            f" lowest free of {PORT_POOL.start}–{PORT_POOL.stop - 1} otherwise)"
        ),
    )
    add_modules(p)
    p.set_defaults(func=cmd_start)

    # stop
    p = sub.add_parser(
        "stop", help="Stop an instance and remove its route and environment"
    )
    add_project(p, "Instance to stop (auto-detected when only one is running)")
    p.set_defaults(func=cmd_stop)

    # restart
    p = sub.add_parser(
        "restart",
        help="Stop then start an instance",
        description=(
            "With -p: rebuild the instance environment (like start -p) and relaunch."
            " Without -p: relaunch the single running instance on its existing"
            " environment (fast path for the dev loop)."
        ),
    )
    add_project(p, "Instance to restart (auto-detected when only one is running)")
    p.add_argument(
        "-d", "--database", metavar="DB", help="Database (default: from PID file)"
    )
    p.add_argument(
        "-P", "--port", metavar="PORT", type=int, help="Port (default: from PID file)"
    )
    add_modules(p)
    p.set_defaults(func=cmd_restart)

    # status
    p = sub.add_parser("status", help="Show container and instance status")
    add_project(p, "Show one instance (default: table of all running instances)")
    p.add_argument("--json", action="store_true", help="Output as JSON")
    p.set_defaults(func=cmd_status)

    # logs
    p = sub.add_parser("logs", help="Show an instance's log")
    add_project(p, "Instance (auto-detected when only one is running)")
    p.add_argument(
        "-n", "--lines", type=int, default=100, metavar="N", help="Lines (default 100)"
    )
    p.add_argument("-f", "--follow", action="store_true", help="Follow (Ctrl+C to end)")
    p.set_defaults(func=cmd_logs)

    # pip
    p = sub.add_parser("pip", help="pip install into the container (all instances)")
    p.add_argument("packages", nargs="+", help="Package names (e.g. pandas xlrd)")
    p.set_defaults(func=cmd_pip)

    # shell
    p = sub.add_parser("shell", help="Open an interactive Odoo Python shell")
    add_project(
        p,
        "Use this instance's addons (built if missing); DB defaults to the instance's",
    )
    p.add_argument("-d", "--database", metavar="DB", help="Database to use")
    p.set_defaults(func=cmd_shell)

    # exec
    p = sub.add_parser("exec", help="Run a command inside the container")
    add_project(
        p,
        "Set ODOO_RC so `odoo` in the command uses this instance's addons"
        " (environment built if missing; `stop -p` removes it)",
    )
    p.add_argument(
        "cmd",
        nargs=argparse.REMAINDER,
        help="Command and arguments (put -- before it)",
    )
    p.set_defaults(func=cmd_exec)

    # workon
    p = sub.add_parser(
        "workon",
        help="Open a shell to run a project's Odoo by hand, served via Traefik",
        description=_workon_help(),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("project", metavar="PROJECT", help="container_configs/PROJECT.txt")
    p.set_defaults(func=cmd_workon)

    # check
    p = sub.add_parser(
        "check",
        help="Statically validate modules before installing (no DB, seconds)",
        description=(
            "Resolves the modules and their transitive dependencies against the"
            " addons path and reports missing modules, missing"
            " external_dependencies.python packages, and manifest `excludes`"
            " conflicts. Runs in the container without a database."
        ),
    )
    add_project(
        p,
        "Resolve against PROJECT's addons path; without -i, check all its modules",
    )
    p.add_argument(
        "-i", "--install", nargs="+", metavar="MODULE", help="Modules to check"
    )
    p.add_argument("--json", action="store_true", help="Output as JSON")
    p.set_defaults(func=cmd_check)

    return parser


def main():
    sys.stdout.reconfigure(line_buffering=True)
    args = build_parser().parse_args()
    try:
        args.func(args)
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)
    except KeyboardInterrupt:
        print()
        sys.exit(0)


if __name__ == "__main__":
    main()
